use_frameworks!

target 'PhysicalButton_Example' do
  pod 'PhysicalButton', :path => '../'

  target 'PhysicalButton_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
